### ISSUE TITLE
Encounter TypeError when running 

### ISSUE THREAD

**Issue by cychong9228** [mlindauer/AutoFolio#6]
When try running the toyexample, I had encountered the TypeError for train_scenario

![image](https://user-images.githubusercontent.com/25782882/42197066-9b196060-7eb3-11e8-85e9-2b01ca21f003.png)

If I were to run the toyexample with the -t parameter, encounter another TypeError : sequence item 0: expected str instance, bool found

![image](https://user-images.githubusercontent.com/25782882/42197114-df8d6f02-7eb3-11e8-8a20-8afd133dce1f.png)

Could the reason because I am running on python 3.6.5?

**Comment by mlindauer** [comment]
Sorry, the issue is related to a bug in the configspace package. We have a hot fix in the development branch of SMAC3. https://github.com/automl/SMAC3

Since we are hunting another bug in SMAC3 (which should not affect AutoFolio), we have not released SMAC3 with the current fixes. So for the moment, the only solution is to use the dev branch of SMAC3.

Best,
Marius

**Comment by mlindauer** [comment]
That's surprising.
Have you tried to first uninstall smac? 
```pip uninstall smac``` (run it until it tells you that smac is not installed)
and afterwards, please try to install SMAC's dev branch again.

**Comment by cychong9228** [comment]
Hi Marius

I am pretty sure that I had uninstalled smac and reinstall the dev version.
I am pasting the steps that I had gone through, along with the error message


**:/Desktop/AutoFolio-master/examples/toy_example_csv$ sudo -H pip3 uninstall smac**
Uninstalling smac-0.8.0:
  /usr/local/bin/smac
  /usr/local/lib/python3.6/dist-packages/smac-0.8.0.egg-info
  /usr/local/lib/python3.6/dist-packages/smac/__init__.py
  /usr/local/lib/python3.6/dist-packages/smac/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/__pycache__/__version__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/__pycache__/smac_cli.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/__version__.py
  /usr/local/lib/python3.6/dist-packages/smac/configspace/__init__.py
  /usr/local/lib/python3.6/dist-packages/smac/configspace/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/configspace/__pycache__/util.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/configspace/util.py
  /usr/local/lib/python3.6/dist-packages/smac/epm/__init__.py
  /usr/local/lib/python3.6/dist-packages/smac/epm/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/epm/__pycache__/base_epm.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/epm/__pycache__/base_imputor.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/epm/__pycache__/random_epm.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/epm/__pycache__/rf_with_instances.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/epm/__pycache__/rfr_imputator.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/epm/__pycache__/uncorrelated_mo_rf_with_instances.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/epm/base_epm.py
  /usr/local/lib/python3.6/dist-packages/smac/epm/base_imputor.py
  /usr/local/lib/python3.6/dist-packages/smac/epm/random_epm.py
  /usr/local/lib/python3.6/dist-packages/smac/epm/rf_with_instances.py
  /usr/local/lib/python3.6/dist-packages/smac/epm/rfr_imputator.py
  /usr/local/lib/python3.6/dist-packages/smac/epm/uncorrelated_mo_rf_with_instances.py
  /usr/local/lib/python3.6/dist-packages/smac/facade/__init__.py
  /usr/local/lib/python3.6/dist-packages/smac/facade/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/facade/__pycache__/epils_facade.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/facade/__pycache__/func_facade.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/facade/__pycache__/hydra_facade.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/facade/__pycache__/psmac_facade.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/facade/__pycache__/roar_facade.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/facade/__pycache__/smac_facade.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/facade/epils_facade.py
  /usr/local/lib/python3.6/dist-packages/smac/facade/func_facade.py
  /usr/local/lib/python3.6/dist-packages/smac/facade/hydra_facade.py
  /usr/local/lib/python3.6/dist-packages/smac/facade/psmac_facade.py
  /usr/local/lib/python3.6/dist-packages/smac/facade/roar_facade.py
  /usr/local/lib/python3.6/dist-packages/smac/facade/smac_facade.py
  /usr/local/lib/python3.6/dist-packages/smac/initial_design/__init__.py
  /usr/local/lib/python3.6/dist-packages/smac/initial_design/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/initial_design/__pycache__/default_configuration_design.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/initial_design/__pycache__/initial_design.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/initial_design/__pycache__/multi_config_initial_design.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/initial_design/__pycache__/random_configuration_design.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/initial_design/__pycache__/single_config_initial_design.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/initial_design/default_configuration_design.py
  /usr/local/lib/python3.6/dist-packages/smac/initial_design/initial_design.py
  /usr/local/lib/python3.6/dist-packages/smac/initial_design/multi_config_initial_design.py
  /usr/local/lib/python3.6/dist-packages/smac/initial_design/random_configuration_design.py
  /usr/local/lib/python3.6/dist-packages/smac/initial_design/single_config_initial_design.py
  /usr/local/lib/python3.6/dist-packages/smac/intensification/__init__.py
  /usr/local/lib/python3.6/dist-packages/smac/intensification/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/intensification/__pycache__/intensification.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/intensification/intensification.py
  /usr/local/lib/python3.6/dist-packages/smac/optimizer/__init__.py
  /usr/local/lib/python3.6/dist-packages/smac/optimizer/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/optimizer/__pycache__/acquisition.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/optimizer/__pycache__/ei_optimization.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/optimizer/__pycache__/epils.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/optimizer/__pycache__/objective.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/optimizer/__pycache__/pSMAC.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/optimizer/__pycache__/random_configuration_chooser.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/optimizer/__pycache__/smbo.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/optimizer/acquisition.py
  /usr/local/lib/python3.6/dist-packages/smac/optimizer/ei_optimization.py
  /usr/local/lib/python3.6/dist-packages/smac/optimizer/epils.py
  /usr/local/lib/python3.6/dist-packages/smac/optimizer/objective.py
  /usr/local/lib/python3.6/dist-packages/smac/optimizer/pSMAC.py
  /usr/local/lib/python3.6/dist-packages/smac/optimizer/random_configuration_chooser.py
  /usr/local/lib/python3.6/dist-packages/smac/optimizer/smbo.py
  /usr/local/lib/python3.6/dist-packages/smac/runhistory/__init__.py
  /usr/local/lib/python3.6/dist-packages/smac/runhistory/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/runhistory/__pycache__/runhistory.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/runhistory/__pycache__/runhistory2epm.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/runhistory/runhistory.py
  /usr/local/lib/python3.6/dist-packages/smac/runhistory/runhistory2epm.py
  /usr/local/lib/python3.6/dist-packages/smac/scenario/__init__.py
  /usr/local/lib/python3.6/dist-packages/smac/scenario/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/scenario/__pycache__/scenario.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/scenario/scenario.py
  /usr/local/lib/python3.6/dist-packages/smac/smac_cli.py
  /usr/local/lib/python3.6/dist-packages/smac/stats/__init__.py
  /usr/local/lib/python3.6/dist-packages/smac/stats/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/stats/__pycache__/stats.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/stats/stats.py
  /usr/local/lib/python3.6/dist-packages/smac/tae/__init__.py
  /usr/local/lib/python3.6/dist-packages/smac/tae/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/tae/__pycache__/execute_func.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/tae/__pycache__/execute_ta_run.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/tae/__pycache__/execute_ta_run_aclib.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/tae/__pycache__/execute_ta_run_hydra.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/tae/__pycache__/execute_ta_run_old.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/tae/execute_func.py
  /usr/local/lib/python3.6/dist-packages/smac/tae/execute_ta_run.py
  /usr/local/lib/python3.6/dist-packages/smac/tae/execute_ta_run_aclib.py
  /usr/local/lib/python3.6/dist-packages/smac/tae/execute_ta_run_hydra.py
  /usr/local/lib/python3.6/dist-packages/smac/tae/execute_ta_run_old.py
  /usr/local/lib/python3.6/dist-packages/smac/utils/__init__.py
  /usr/local/lib/python3.6/dist-packages/smac/utils/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/utils/__pycache__/constants.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/utils/__pycache__/duplicate_filter_logging.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/utils/__pycache__/logging.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/utils/__pycache__/merge_foreign_data.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/utils/__pycache__/test_helpers.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/utils/__pycache__/util_funcs.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/utils/__pycache__/validate.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/utils/constants.py
  /usr/local/lib/python3.6/dist-packages/smac/utils/duplicate_filter_logging.py
  /usr/local/lib/python3.6/dist-packages/smac/utils/io/__init__.py
  /usr/local/lib/python3.6/dist-packages/smac/utils/io/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/utils/io/__pycache__/cmd_reader.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/utils/io/__pycache__/input_reader.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/utils/io/__pycache__/output_directory.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/utils/io/__pycache__/output_writer.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/utils/io/__pycache__/traj_logging.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/smac/utils/io/cmd_reader.py
  /usr/local/lib/python3.6/dist-packages/smac/utils/io/input_reader.py
  /usr/local/lib/python3.6/dist-packages/smac/utils/io/output_directory.py
  /usr/local/lib/python3.6/dist-packages/smac/utils/io/output_writer.py
  /usr/local/lib/python3.6/dist-packages/smac/utils/io/traj_logging.py
  /usr/local/lib/python3.6/dist-packages/smac/utils/logging.py
  /usr/local/lib/python3.6/dist-packages/smac/utils/merge_foreign_data.py
  /usr/local/lib/python3.6/dist-packages/smac/utils/test_helpers.py
  /usr/local/lib/python3.6/dist-packages/smac/utils/util_funcs.py
  /usr/local/lib/python3.6/dist-packages/smac/utils/validate.py
  /usr/local/lib/python3.6/dist-packages/test/test_cli/__init__.py
  /usr/local/lib/python3.6/dist-packages/test/test_cli/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_cli/__pycache__/random_configuration_chooser_impl.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_cli/__pycache__/test_deterministic_smac.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_cli/__pycache__/test_restore_state.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_cli/random_configuration_chooser_impl.py
  /usr/local/lib/python3.6/dist-packages/test/test_cli/test_deterministic_smac.py
  /usr/local/lib/python3.6/dist-packages/test/test_cli/test_restore_state.py
  /usr/local/lib/python3.6/dist-packages/test/test_configspace/__init__.py
  /usr/local/lib/python3.6/dist-packages/test/test_configspace/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_configspace/__pycache__/test_configspace.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_configspace/test_configspace.py
  /usr/local/lib/python3.6/dist-packages/test/test_epm/__init__.py
  /usr/local/lib/python3.6/dist-packages/test/test_epm/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_epm/__pycache__/test_rfr_with_instances.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_epm/__pycache__/test_uncorrelated_mo_rf_with_instances.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_epm/test_rfr_with_instances.py
  /usr/local/lib/python3.6/dist-packages/test/test_epm/test_uncorrelated_mo_rf_with_instances.py
  /usr/local/lib/python3.6/dist-packages/test/test_facade/__init__.py
  /usr/local/lib/python3.6/dist-packages/test/test_facade/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_facade/__pycache__/test_func_facade.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_facade/__pycache__/test_hydra_facade.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_facade/__pycache__/test_psmac_facade.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_facade/__pycache__/test_roar_facade.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_facade/__pycache__/test_smac_facade.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_facade/test_func_facade.py
  /usr/local/lib/python3.6/dist-packages/test/test_facade/test_hydra_facade.py
  /usr/local/lib/python3.6/dist-packages/test/test_facade/test_psmac_facade.py
  /usr/local/lib/python3.6/dist-packages/test/test_facade/test_roar_facade.py
  /usr/local/lib/python3.6/dist-packages/test/test_facade/test_smac_facade.py
  /usr/local/lib/python3.6/dist-packages/test/test_initial_design/__init__.py
  /usr/local/lib/python3.6/dist-packages/test/test_initial_design/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_initial_design/__pycache__/test_multiple_config_initial_design.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_initial_design/__pycache__/test_single_config_initial_design.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_initial_design/test_multiple_config_initial_design.py
  /usr/local/lib/python3.6/dist-packages/test/test_initial_design/test_single_config_initial_design.py
  /usr/local/lib/python3.6/dist-packages/test/test_integration/__init__.py
  /usr/local/lib/python3.6/dist-packages/test/test_integration/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_integration/__pycache__/eips.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_integration/eips.py
  /usr/local/lib/python3.6/dist-packages/test/test_intensify/__init__.py
  /usr/local/lib/python3.6/dist-packages/test/test_intensify/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_intensify/__pycache__/test_intensify.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_intensify/test_intensify.py
  /usr/local/lib/python3.6/dist-packages/test/test_runhistory/__init__.py
  /usr/local/lib/python3.6/dist-packages/test/test_runhistory/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_runhistory/__pycache__/test_rfr_imputor.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_runhistory/__pycache__/test_runhistory.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_runhistory/__pycache__/test_runhistory2epm.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_runhistory/test_rfr_imputor.py
  /usr/local/lib/python3.6/dist-packages/test/test_runhistory/test_runhistory.py
  /usr/local/lib/python3.6/dist-packages/test/test_runhistory/test_runhistory2epm.py
  /usr/local/lib/python3.6/dist-packages/test/test_scenario/__init__.py
  /usr/local/lib/python3.6/dist-packages/test/test_scenario/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_scenario/__pycache__/test_scenario.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_scenario/test_scenario.py
  /usr/local/lib/python3.6/dist-packages/test/test_smbo/__init__.py
  /usr/local/lib/python3.6/dist-packages/test/test_smbo/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_smbo/__pycache__/test_acquisition.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_smbo/__pycache__/test_ei_optimization.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_smbo/__pycache__/test_epils.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_smbo/__pycache__/test_pSMAC.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_smbo/__pycache__/test_random_configuration_chooser.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_smbo/__pycache__/test_smbo.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_smbo/test_acquisition.py
  /usr/local/lib/python3.6/dist-packages/test/test_smbo/test_ei_optimization.py
  /usr/local/lib/python3.6/dist-packages/test/test_smbo/test_epils.py
  /usr/local/lib/python3.6/dist-packages/test/test_smbo/test_pSMAC.py
  /usr/local/lib/python3.6/dist-packages/test/test_smbo/test_random_configuration_chooser.py
  /usr/local/lib/python3.6/dist-packages/test/test_smbo/test_smbo.py
  /usr/local/lib/python3.6/dist-packages/test/test_tae/__init__.py
  /usr/local/lib/python3.6/dist-packages/test/test_tae/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_tae/__pycache__/dummy_ta_wrapper.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_tae/__pycache__/dummy_ta_wrapper_aclib.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_tae/__pycache__/test_exec_func.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_tae/__pycache__/test_exec_tae_run.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_tae/__pycache__/test_tae_aclib.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_tae/__pycache__/test_tae_old.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_tae/dummy_ta_wrapper.py
  /usr/local/lib/python3.6/dist-packages/test/test_tae/dummy_ta_wrapper_aclib.py
  /usr/local/lib/python3.6/dist-packages/test/test_tae/test_exec_func.py
  /usr/local/lib/python3.6/dist-packages/test/test_tae/test_exec_tae_run.py
  /usr/local/lib/python3.6/dist-packages/test/test_tae/test_tae_aclib.py
  /usr/local/lib/python3.6/dist-packages/test/test_tae/test_tae_old.py
  /usr/local/lib/python3.6/dist-packages/test/test_utils/__init__.py
  /usr/local/lib/python3.6/dist-packages/test/test_utils/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_utils/__pycache__/test_validate.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_utils/io/__init__.py
  /usr/local/lib/python3.6/dist-packages/test/test_utils/io/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_utils/io/__pycache__/test_CMDReader.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_utils/io/__pycache__/test_inputreader.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_utils/io/__pycache__/test_traj_logging.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/test/test_utils/io/test_CMDReader.py
  /usr/local/lib/python3.6/dist-packages/test/test_utils/io/test_inputreader.py
  /usr/local/lib/python3.6/dist-packages/test/test_utils/io/test_traj_logging.py
  /usr/local/lib/python3.6/dist-packages/test/test_utils/test_validate.py
Proceed (y/n)? y
  Successfully uninstalled smac-0.8.0
**:/Desktop/AutoFolio-master/examples/toy_example_csv$ sudo -H pip3 install git+https://github.com/automl/SMAC3.git@development**
Collecting git+https://github.com/automl/SMAC3.git@development
  Cloning https://github.com/automl/SMAC3.git (to development) to /tmp/pip-7u6zho2z-build
Requirement already satisfied: ConfigSpace<0.5,>=0.4.6 in /usr/local/lib/python3.6/dist-packages (from smac==0.8.0)
Requirement already satisfied: cython in /usr/local/lib/python3.6/dist-packages (from smac==0.8.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.6/dist-packages (from smac==0.8.0)
Requirement already satisfied: nose>=1.3.0 in /usr/local/lib/python3.6/dist-packages (from smac==0.8.0)
Requirement already satisfied: numpy>=1.7.1 in /usr/local/lib/python3.6/dist-packages (from smac==0.8.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.6/dist-packages (from smac==0.8.0)
Requirement already satisfied: pynisher>=0.4.1 in /usr/local/lib/python3.6/dist-packages (from smac==0.8.0)
Requirement already satisfied: pyrfr>=0.5.0 in /usr/local/lib/python3.6/dist-packages (from smac==0.8.0)
Requirement already satisfied: scikit-learn>=0.18.0 in /usr/local/lib/python3.6/dist-packages (from smac==0.8.0)
Requirement already satisfied: scipy>=0.18.1 in /usr/local/lib/python3.6/dist-packages (from smac==0.8.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from smac==0.8.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from smac==0.8.0)
Requirement already satisfied: sphinx in /usr/local/lib/python3.6/dist-packages (from smac==0.8.0)
Requirement already satisfied: sphinx_rtd_theme in /usr/local/lib/python3.6/dist-packages (from smac==0.8.0)
Requirement already satisfied: typing in /usr/local/lib/python3.6/dist-packages (from smac==0.8.0)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.6/dist-packages (from ConfigSpace<0.5,>=0.4.6->smac==0.8.0)
Requirement already satisfied: docutils>=0.3 in /usr/local/lib/python3.6/dist-packages (from pynisher>=0.4.1->smac==0.8.0)
Requirement already satisfied: babel!=2.0,>=1.3 in /usr/local/lib/python3.6/dist-packages (from sphinx->smac==0.8.0)
Requirement already satisfied: imagesize in /usr/local/lib/python3.6/dist-packages (from sphinx->smac==0.8.0)
Requirement already satisfied: requests>=2.0.0 in /usr/lib/python3/dist-packages (from sphinx->smac==0.8.0)
Requirement already satisfied: Pygments>=2.0 in /usr/local/lib/python3.6/dist-packages (from sphinx->smac==0.8.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/dist-packages (from sphinx->smac==0.8.0)
Requirement already satisfied: Jinja2>=2.3 in /usr/local/lib/python3.6/dist-packages (from sphinx->smac==0.8.0)
Requirement already satisfied: alabaster<0.8,>=0.7 in /usr/local/lib/python3.6/dist-packages (from sphinx->smac==0.8.0)
Requirement already satisfied: snowballstemmer>=1.1 in /usr/local/lib/python3.6/dist-packages (from sphinx->smac==0.8.0)
Requirement already satisfied: sphinxcontrib-websupport in /usr/local/lib/python3.6/dist-packages (from sphinx->smac==0.8.0)
Requirement already satisfied: pytz>=0a in /usr/lib/python3/dist-packages (from babel!=2.0,>=1.3->sphinx->smac==0.8.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from Jinja2>=2.3->sphinx->smac==0.8.0)
Installing collected packages: smac
  Running setup.py install for smac ... done
Successfully installed smac-0.8.0
**:/Desktop/AutoFolio-master/examples/toy_example_csv$ python3 /home/chong/Desktop/AutoFolio-master/scripts/autofolio --perf perf.csv --feature_csv feats.csv**
/usr/local/lib/python3.6/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
INFO:AutoFolio:CV-Iteration: 1
INFO:AutoFolio:CV-Iteration: 1
INFO:AutoFolio:Given Configuration: Configuration:
  StandardScaler, Value: True
  classifier, Value: 'RandomForest'
  fgroup_all, Value: True
  imputer_strategy, Value: 'mean'
  pca, Value: False
  rf:bootstrap, Value: True
  rf:criterion, Value: 'gini'
  rf:max_depth, Value: 2147483648
  rf:max_features, Value: 'sqrt'
  rf:min_samples_leaf, Value: 10
  rf:min_samples_split, Value: 2
  rf:n_estimators, Value: 10
  selector, Value: 'PairwiseClassifier'

INFO:PairwiseClassifier:Fit PairwiseClassifier with <class 'autofolio.selector.classifiers.random_forest.RandomForest'>
INFO:AutoFolio:Predict on Test
Traceback (most recent call last):
  File "/home/chong/Desktop/AutoFolio-master/scripts/autofolio", line 19, in <module>
    af.run_cli()
  File "/home/chong/Desktop/AutoFolio-master/autofolio/autofolio.py", line 143, in run_cli
    self.run_cv(config=config, scenario=scenario, folds=int(scenario.cv_data.max().max()))
  File "/home/chong/Desktop/AutoFolio-master/autofolio/autofolio.py", line 545, in run_cv
    fold=i)
  File "/home/chong/Desktop/AutoFolio-master/autofolio/autofolio.py", line 607, in run_fold
    schedules=schedules, test_scenario=test_scenario, train_scenario=training_scenario)
TypeError: validate_quality() got an unexpected keyword argument 'train_scenario'

**Comment by mlindauer** [comment]
Sorry, I overlooked that you reported two issues.
The one was fixed by using SMAC's dev branch.
The other one needed to be fixed in AutoFolio's code which I did now.

Cheers,
Marius

**Comment by cychong9228** [comment]
Hi Marius,

Thanks! It is working perfectly now. Thanks for fixing the bug
